### PR TITLE
Needed a true inverse transform for more exotic operations.

### PR DESCRIPTION
**Pull request by BradWBeer**

### CODE REVIEW

**Comment by cbaggers** [comment]
Heya! Good stuff on the inverse work. Like it and especially the fact that it makes the naming more correct and consistent.

However I'm not going to merge the change to the orthographic projection: https://en.wikipedia.org/wiki/Orthographic_projection. Can you remove that change? After that I'm happy to pull.

**Comment by BradWBeer** [comment]
Undid projection change...

**Comment by cbaggers** [comment]
hehe still seems a bit off https://github.com/BradWBeer/rtg-math/blob/master/projection.lisp

**Comment by cbaggers** [comment]
Never mind, I pulled it and fixed it on my end.

thanks again!

**Pull request closed without merging**
